name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run check | tee test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: [self-hosted, windows, xfusion]

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Show test results
        run: type test-results.txt

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploy step running on Windows runner"
